apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: cluster
spec:
  featureSet: TechPreviewNoUpgrade 
